### ISSUE TITLE
login error when upgrading

### ISSUE THREAD

**Issue by kalaklanar** [kawarimidoll/bluestream#25]
I've been running an old version of bluestream for a while now (from commit #13) with no issues. I downloaded the latest code, copied the .env from the old directory to the new one, and am getting the following error: 

`Watcher Process started.
error: Uncaught (in promise) Error: Invalid identifier or password
    at ServiceClient.call (file:///home/jackie/.cache/deno/npm/registry.npmjs.org/@atproto/api/0.6.20/dist/index.js:15582:15)
    at eventLoopTick (ext:core/01_core.js:168:7)
    at async BskyAgent.login (file:///home/jackie/.cache/deno/npm/registry.npmjs.org/@atproto/api/0.6.20/dist/index.js:26483:19)
    at async login (file:///usr/local/src/bluestream.git/login.ts:33:3)
    at async file:///usr/local/src/bluestream.git/server.ts:21:15`

I've recreated the deno cache (rm -fr /home/jackie/.cache/deno) and still no luck. I can go right back to the old version, and it works fine. Did something change about the .env file format? Was there some kind of bug introduced when the login was refactored? I'm stumped as to why the old version works, but the new one doesn't

**Comment by kalaklanar** [comment]
I finally circled back to fix this: the password needs quotes around it with the newer code commit:
BLUESKY_IDENTIFIER=<yourusernamehere>.bsky.social
BLUESKY_PASSWORD="<yourpasswordhere>"
